### ISSUE TITLE
Problems with some mods when it comes to cross os play between window and linux/mac os

### ISSUE THREAD

**Issue by Parexy** [Parexy/Multiplayer#40] opened 2019-04-10 22:16 UTC
Some mods cause hash_diff when connecting if you are doing cross os play. 

From what i understand this is caused by the case sensitivity of linux and mac os (Could be something else), but it makes a hash_diff appear even though their files technically are identical.

![image](https://user-images.githubusercontent.com/46968966/55917061-6ff23880-5bee-11e9-8e56-b4ddb36992ce.png)

**Comment by MilanDierick** [comment] 2019-04-10 23:17
@Parexy What mods where being used when this issue appeared?

**Comment by Parexy** [comment] 2019-04-10 23:21
@MilanDierick "Expanded Prosthetics and Organ Engineering" was the mod that caused the problem for the most recent group people which this happend to.
The windows users could connect without a problem but the mac user couldn't.

**Comment by MilanDierick** [comment] 2019-04-10 23:22
@Parexy I'll ask around tomorrow if someone has a mac that we can test this with.

**Comment by vasilevp** [comment] 2019-04-11 14:22
If anyone's interested, [here](https://github.com/Zetrith/Multiplayer/pull/34)'s a workaround that I came up with some time ago to crossplay with a friend. I never encountered issues with this approach, but it can potentially require additional restrictions on mod order, etc.
_UPD: It's worth noting that this workaround is not backwards compatible._

**Comment by Pecius** [comment] 2019-04-11 16:48
The issue indeed runs deeper as Zetrith said. 
Since your solution fixes the hash problem by sorting lists with defs, it means that there's a difference in order in `defsList` of `DefDatabase`. Which would mean it can actually affect more things than just that hash as IEnumerable `AllDefs` (which points at defsList) is used in many places of RimWorld's code, including random selection. So there's a probability the issue will cause desyncs in other mods.
I have traced a possible cause, but I have to do some tests first.

**Comment by SweptWasTaken** [comment] 2019-04-11 17:05
I can do testing with a mac as well if needed.

**Comment by vasilevp** [comment] 2019-04-12 16:03
The issue appears on Linux as well (as long as you use the ext* filesystem), so you don't need a Mac specifically. Might be easier for the devs to test that way.

**Comment by rkost** [comment] 2019-06-01 21:21
> The issue appears on Linux as well (as long as you use the ext* filesystem), so you don't need a Mac specifically. Might be easier for the devs to test that way.

Can confirm for linux (arch) with btrfs as a host and windows as a client. I know that for RimWorld `1.0.2150` there was [this fork/release](https://github.com/vasilevp/Multiplayer/releases/tag/v0.4.4-linuxcompat) that fixed the issue (however i did not investigate which commit was fixing it specifically). 

I would also be ready to test stuff if you need some helping hands.

EDIT: Sorry, I just saw that you @vasilevp are here also. So I guess there are new problems for the new RimWorld version...

**Comment by notfood** [comment] 2019-06-04 22:09
Please try https://github.com/notfood/RimWorld-Multiplayer/commit/099db82ae903231753b5eb9597d2970f0348cb9b

This needs testing, both host and client need it. Here is a compiled dll with the feature: [Multiplayer.zip](https://github.com/Parexy/Multiplayer/files/3254652/Multiplayer.zip)

**Comment by rkost** [comment] 2019-06-05 21:02
I can confirm that the changes of @notfood do work for arch `linux 5.1.4` with `btrfs` as a host and Windows 10 as a client when applied to the current release (`0.4.7.1`).

Thanks for the fix!

**Comment by SamboyCoding** [comment] 2019-06-08 14:52
Fixed via #83 which includes notfood's patch.

**Closed as completed by SamboyCoding** 2019-06-08 14:52 UTC
Labels: bug
