### ISSUE TITLE
Free-sync and G-sync causes problems with the tick rate

### ISSUE THREAD

**Issue by Parexy** [Parexy/Multiplayer#28] opened 2019-04-05 20:28 UTC
- [ ] Search the code base and see how tick rate is being handled, to see if Free-sync/G-sync can influence this
- [ ] Server ticks at about 16.66... ms / tick (MultiplayerServer:107) What if client refresh rate is lower than server tick rate?

**Comment by MilanDierick** [comment] 2019-04-05 21:00
@Parexy Could you attach a replay file in which this bug is happening? I could try and reproduce the issue because I have a G-sync monitor as well.

**Comment by Parexy** [comment] 2019-04-06 12:42
I don't have a g-sync or free-sync monitor so i would have to connect to you while you have it enabled for us to get a replay file with info about it in.

**Comment by MilanDierick** [comment] 2019-04-06 12:44
But why don't you ask the replay file if the people who are experiencing these issues?

**Comment by Parexy** [comment] 2019-04-06 13:04
Well right now im just adding issues that i have helped people resolve before so you and other people know that they are known problems. It's also a part of my standard response to say that they have to disable free-sync/g-sync if enabled together with some other stuff and they rarely know/say what specifically caused their problem unless it was caused by a mod. And the people that i know had that specific problem i probably wouldn't even be able to find through all of the other support i have given out as it has been over a week since i last helped somone with it.

**Comment by MilanDierick** [comment] 2019-04-06 13:13
I'm happy that you are able to resolve problems for those people, but when you make a GitHub issue, you are indicating that there is a bug, but you don't specify any details, so how are we going to fix the bug without any information? I've already looked at how the server handles tick rates internally, and I don't see how the refresh rate of a monitor affects the connection between a client and the server. If we can't identify the issue, we'll have to close down the issue.

**Comment by YellowOnion** [comment] 2019-05-06 02:36
Gsync/Freesync should allow the game to run a head of the server if the games tick is somehow connected to the fresh rate of the monitor.

A quick google of "gsync rimworld" shows a lot of people talking about issues, perhaps the game self is to blame?

Edit: Also, That eventloop is awful, you're sleeping for a fix length of time, 10ms, and then burning the rest of the time 6ms doing nothing useful.

it should just do `TickNet()` and `Tick()`, then sleep the *remainder* of the time.

**Comment by MilanDierick** [comment] 2019-05-06 15:33
@YellowOnion I don't know how familiar you are with G-Sync and FreeSync, but how it works is as follows: the refresh rate of the monitor is reduced to the point where it matches the frame rate of the GPU. This prevents screen tearing, thus improving visual quality. Tynan has overridden a lot of the logic of the Unity Engine, but the game logic is still separate from the graphics rendering. This means that having a G-Sync monitor should not affect the performance of the game, since it isn't influencing the frame rate of the game. The people that are reporting issues with G-Sync monitors most likely have made changes in their NVidea settings, which result in degraded performance. I am using a 1440p 165Hz G-Sync monitor myself, and I have no issues playing the game with G-Sync enabled. I can force the game to run at exactly 22 fps by toggling specific settings, but I forgot which ones. 

When following my previous explanation, a G-Sync monitor shouldn't allow the game to run ahead of the server, since the refresh rate of the monitor is not controlling the game. The game tick rate is not controlled by the refresh rate of the monitor. 

We know that the event loop is funky. It has been written by Zetrith, and we are not sure why he has implemented it this way. He is not stupid, so we are not sure if he implemented it this way because he needed to get things done quickly, or if there is more reasoning behind it.

**Comment by YellowOnion** [comment] 2019-05-07 01:50
@MilanDierick I understand how these modes work, I remember Terraria use to have some issues when Vsync was force disabled, because game logic was timed to the monitor for some reason. Obviously you want a colonist to walk from 1 tile to another in a fixed amount of time, but you also want that animation integrated at 165hz or 240hz time steps so it looks ultra smooth, if there's a bug you could have issues when synchronising the two.

> we are not sure why he has implemented it this way

I was gonna try rewrite it, but I can't get VSCode to find the references despite them being in the correct folders.

**Comment by MilanDierick** [comment] 2019-05-18 20:33
Closing this because reports of this issue are very sporadic, and no desync files have been provided to this issue.

**Closed as completed by MilanDierick** 2019-05-18 20:33 UTC
Labels: bug
